campus: NREL
application: FDD.FCU.model.oad_svm.Application
output_file: ''
arguments:
  model_path: "./FDD/FCU/model/oad_svm.pkl"
  device_type: FCU
  analysis_name: oad
  sensitivity: default
  point_mapping:
    outdoor_air_humidity: Fan_Coil_Unit_Outdoor_Air_Humidity
    mixed_air_humidity: Fan_Coil_Unit_Mixed_Air_Humidity
    return_air_humidity: Fan_Coil_Unit_Return_Air_Humidity
    discharge_air_humidity: Fan_Coil_Unit_Discharge_Air_Humidity
    outdoor_air_temperature: Fan_Coil_Unit_Outside_Air_Temperature
    mixed_air_temperature: Fan_Coil_Unit_Mixed_Air_Temperature
    return_air_temperature: Fan_Coil_Unit_Return_Air_Temperature
    discharge_air_temperature: Fan_Coil_Unit_Discharge_Air_Temperature
    heating_coil_return_water_temperature: Fan_Coil_Unit_Return_Water_Heating_Temperature
    cooling_coil_return_water_temperature: Fan_Coil_Unit_Return_Water_Cooling_Temperature
    room_temperature: Room_Temperature
    discharge_air_mass_flow: Fan_Coil_Unit_Discharge_Air_Flow
    timestamp: Date_Time
    fault: Fault_Status